CREATE DATABASE pesquisa COLLATE 'utf8mb4_unicode_ci';

CREATE TABLE IF NOT EXISTS `1pesquisa` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `ocorrencia_contato_nome` varchar(50) NOT NULL,
  `ocorrencia_contato_fone` varchar(50) NOT NULL,
  `ocorrencia_solicitante_nome` varchar(50) NOT NULL,
  `ocorrencia_solicitante_fone` varchar(50) NOT NULL,
  `ocorrencia_ocorrencia_id` int(100) NOT NULL,
  `cliente_sigla` varchar(50) NOT NULL,
  `municipio_nome` varchar(50) NOT NULL,
  `total_tempo_gasto` varchar(50) NOT NULL,
  `ocorrencia_data_abertura` varchar(50) NOT NULL,
  `ocorrencia_data_conclusao` varchar(50) NOT NULL,
  `ocorrencia_data_solucao` varchar(50) NOT NULL,
  `ocorrencia_execucoes_data_ini` varchar(50) NOT NULL,
  `ocorrencia_execucoes_data_fim` varchar(50) NOT NULL,
  `funcionario_nome` varchar(50) NOT NULL,
  `ocorrencia_execucoes_forma_atendimento_descricao` varchar(50) NOT NULL,
  `area_sigla` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `1PESQUISACONTATOS` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `SOC` varchar(100) NOT NULL,
  `REGIONAL` varchar(100) NOT NULL,
  `CIDADE` varchar(100) NOT NULL,
  `TELRESID` varchar(100) NOT NULL,
  `TELCOM` varchar(100) NOT NULL,
  `STATUS1` varchar(100) NOT NULL,
  `STATUS2` varchar(100) NOT NULL,
  `STATUS3` varchar(100) NOT NULL,
  `STATUS4` varchar(100) NOT NULL,
  `CONTATO` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `1pesquisaresposta` (
  `id` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'idtabela',
  `idformpesquisada` mediumint(9) NOT NULL,
  `contato` varchar(100) NOT NULL COMMENT 'nome da pessoa que precisou ser atendida',
  `cliente` varchar(100) NOT NULL COMMENT 'nome da secretaria',
  `ndeocorrencia` varchar(100) NOT NULL,
  `Semana` varchar(5) NOT NULL,
  `Ano` int(5) NOT NULL,
  `Pergunta1` varchar(100) NOT NULL COMMENT 'sexo',
  `Pergunta2` varchar(100) NOT NULL COMMENT 'cortesia',
  `Pergunta3` varchar(100) NOT NULL COMMENT 'profissionalismo',
  `pergunta4` varchar(10) NOT NULL COMMENT 'precisao',
  `pergunta5` varchar(10) NOT NULL COMMENT 'esclarecimento',
  `pergunta6` varchar(10) NOT NULL COMMENT 'suporte tecnico',
  `pergunta7` varchar(10) NOT NULL COMMENT 'temposoluc',
  `pergunta8` varchar(10) NOT NULL COMMENT 'qualidade',
  `pergunta9` mediumtext NOT NULL COMMENT 'sugestoes',
  `Pergunta1Pessimo` mediumtext NOT NULL,
  `Pergunta2Pessimo` mediumtext NOT NULL,
  `Pergunta3Pessimo` mediumtext NOT NULL,
  `Pergunta4Pessimo` mediumtext NOT NULL,
  `Pergunta5Pessimo` mediumtext NOT NULL,
  `Pergunta6Pessimo` mediumtext NOT NULL,
  `Pergunta7Pessimo` mediumtext NOT NULL,
  `Pergunta8Pessimo` mediumtext NOT NULL,
  `Data` varchar(100) NOT NULL,
  `IP_USER` varchar(15) NOT NULL,
  `REFERER` varchar(50) NOT NULL,
  `TecnicoLogado` varchar(20) NOT NULL,
  `tecnicoavaliado` varchar(50) NOT NULL COMMENT 'tec que foi avaliado',
  `regional` varchar(50) NOT NULL COMMENT 'regional',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ` 1pesquisaresposta` (
  `id` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'idtabela',
  `idformpesquisada` mediumint(9) NOT NULL,
  `contato` varchar(100) NOT NULL COMMENT 'nome da pessoa que precisou ser atendida',
  `cliente` varchar(100) NOT NULL COMMENT 'nome da secretaria',
  `ndeocorrencia` varchar(100) NOT NULL,
  `Semana` varchar(5) NOT NULL,
  `Ano` int(5) NOT NULL,
  `Pergunta1` varchar(100) NOT NULL COMMENT 'sexo',
  `Pergunta2` varchar(100) NOT NULL COMMENT 'cortesia',
  `Pergunta3` varchar(100) NOT NULL COMMENT 'profissionalismo',
  `pergunta4` varchar(10) NOT NULL COMMENT 'precisao',
  `pergunta5` varchar(10) NOT NULL COMMENT 'esclarecimento',
  `pergunta6` varchar(10) NOT NULL COMMENT 'FACILIDADE',
  `pergunta7` varchar(10) NOT NULL COMMENT 'temposoluc',
  `pergunta8` varchar(10) NOT NULL COMMENT 'qualidade',
  `pergunta9` mediumtext NOT NULL COMMENT 'sugestoes',
  `Pergunta1Pessimo` mediumtext NOT NULL,
  `Pergunta2Pessimo` mediumtext NOT NULL,
  `Pergunta3Pessimo` mediumtext NOT NULL,
  `Pergunta4Pessimo` mediumtext NOT NULL,
  `Pergunta5Pessimo` mediumtext NOT NULL,
  `Pergunta6Pessimo` mediumtext NOT NULL,
  `Pergunta7Pessimo` mediumtext NOT NULL,
  `Pergunta8Pessimo` mediumtext NOT NULL,
  `Data` varchar(100) NOT NULL,
  `IP_USER` varchar(15) NOT NULL,
  `REFERER` varchar(50) NOT NULL,
  `TecnicoLogado` varchar(20) NOT NULL,
  `tecnicoavaliado` varchar(50) NOT NULL COMMENT 'tec que foi avaliado',
  `regional` varchar(50) NOT NULL COMMENT 'regional',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `1pesquisa_amostras_enviadas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `semana` int(50) DEFAULT NULL,
  `num_pesquisa` int(50) DEFAULT NULL,
  `ano` int(50) DEFAULT NULL,
  `soc` varchar(200) DEFAULT NULL,
  `regional` varchar(200) DEFAULT NULL,
  `cidade` varchar(200) DEFAULT NULL,
  `tel_resid` varchar(200) DEFAULT NULL,
  `tel_com` varchar(200) DEFAULT NULL,
  `contato` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `1pesquisa_pamostragem` (
  `id` bigint(255) NOT NULL AUTO_INCREMENT,
  `prioriza_tec_unic_atend` varchar(10) NOT NULL COMMENT 'Qtos tecnico atenderam Prioridade p 1 tec',
  `pesquisa` varchar(100) NOT NULL COMMENT 'numero da semana',
  `contato` varchar(100) NOT NULL,
  `telefone` varchar(100) NOT NULL,
  `solicitante_nome` varchar(100) NOT NULL,
  `solicitante_fone` varchar(100) NOT NULL,
  `ndeocorrencia` int(100) NOT NULL,
  `cliente` varchar(100) NOT NULL,
  `cidade` varchar(100) NOT NULL,
  `tempoatendimento` varchar(100) NOT NULL,
  `dataabertura` datetime NOT NULL,
  `dataconclusao` date NOT NULL,
  `datainicio` datetime NOT NULL,
  `datafim` datetime NOT NULL,
  `tecnico` varchar(100) NOT NULL,
  `formaatendimento` varchar(100) NOT NULL,
  `executor` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
)ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `1pesquisa_sorteio` (
  `id` bigint(255) NOT NULL AUTO_INCREMENT,
  `pesquisa` varchar(100) NOT NULL,
  `contato` varchar(100) NOT NULL,
  `telefone` varchar(100) NOT NULL,
  `solicitante_nome` varchar(100) NOT NULL COMMENT 'nome da pessoa que precisou ser atendida',
  `solicitante_fone` varchar(100) NOT NULL COMMENT 'quem abriu a ordem de serviço - atendedor, dicac, tecnico alocado',
  `ndeocorrencia` int(100) NOT NULL,
  `cliente` varchar(100) NOT NULL,
  `cidade` varchar(100) NOT NULL,
  `tempoatendimento` varchar(100) NOT NULL,
  `dataabertura` datetime NOT NULL,
  `dataconclusao` date NOT NULL,
  `datainicio` datetime NOT NULL,
  `datafim` datetime NOT NULL,
  `tecnico` varchar(100) NOT NULL,
  `formaatendimento` varchar(100) NOT NULL,
  `executor` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `girpesquisaresposta` (
  `id` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'idtabela',
  `idformpesquisada` mediumint(9) NOT NULL,
  `contato` varchar(100) NOT NULL COMMENT 'nome da pessoa que precisou ser atendida',
  `cliente` varchar(100) NOT NULL COMMENT 'nome da secretaria',
  `ndeocorrencia` varchar(100) NOT NULL,
  `Semana` varchar(5) NOT NULL,
  `Ano` int(5) NOT NULL,
  `Pergunta1` varchar(100) NOT NULL COMMENT 'sexo',
  `Pergunta2` varchar(100) NOT NULL COMMENT 'cortesia',
  `Pergunta3` varchar(100) NOT NULL COMMENT 'profissionalismo',
  `pergunta4` varchar(10) NOT NULL COMMENT 'precisao',
  `pergunta5` varchar(10) NOT NULL COMMENT 'esclarecimento',
  `pergunta6` varchar(10) NOT NULL COMMENT 'FACILIDADE',
  `pergunta7` varchar(10) NOT NULL COMMENT 'temposoluc',
  `pergunta8` varchar(10) NOT NULL COMMENT 'qualidade',
  `pergunta9` mediumtext NOT NULL COMMENT 'sugestoes',
  `Pergunta1Pessimo` mediumtext NOT NULL,
  `Pergunta2Pessimo` mediumtext NOT NULL,
  `Pergunta3Pessimo` mediumtext NOT NULL,
  `Pergunta4Pessimo` mediumtext NOT NULL,
  `Pergunta5Pessimo` mediumtext NOT NULL,
  `Pergunta6Pessimo` mediumtext NOT NULL,
  `Pergunta7Pessimo` mediumtext NOT NULL,
  `Pergunta8Pessimo` mediumtext NOT NULL,
  `Data` varchar(100) NOT NULL,
  `IP_USER` varchar(15) NOT NULL,
  `REFERER` varchar(50) NOT NULL,
  `TecnicoLogado` varchar(20) NOT NULL,
  `tecnicoavaliado` varchar(50) NOT NULL COMMENT 'tec que foi avaliado',
  `regional` varchar(50) NOT NULL COMMENT 'regional',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
